university/urls.py
from django import views
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.urlpatterns import format_suffix_patterns
from app import API_Views
# from university import views
from app.views import * 
from app import views
from django.conf.urls import handler404

admin.site.site_header = 'My project'
admin.site.site_title = "Welcom to Admin Panel"
admin.site.index_title="Welcome to this Portal"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/result', API_Views.StudentList.as_view()),
    path("",LoginView.as_view(),name="login"),
    # path("dashboard/",views.dashboard,name="dashboard"),
    # path('dashboard/', StudentCreateView.as_view(), name='dashboard'),
    path('studentdata/',StudentListView.as_view(),name='studentdata'),
    path('university',UniversityCreateView.as_view(),name='university'),
    path('delete/<int:pk>', DeleteView.as_view(),name='delete'),
    path('dashboard/',views.dashboard,name="dashboard")
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

# urlpatterns = format_suffix_patterns(urlpatterns)
handler404 = views.error_404

app/models.py
# from tkinter import CASCADE 
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class University(models.Model):
    id = models.BigAutoField(primary_key=True )
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Student(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    university_name = models.ForeignKey(University,on_delete=models.CASCADE)  
    registration_no = models.IntegerField()
    student_result = models.FileField(upload_to = 'result')

    def __str__(self):
        return str(self.registration_no)
    

app/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model
from django import forms
from .models import *


class LoginForm(AuthenticationForm):
    username = forms.CharField(label='Email')
    
    
class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = '__all__'
        
class UniversityForm(forms.ModelForm):
    class Meta:
        model = University
        fields = '__all__'           

app/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from app.forms import *
from app.models import *
from django.views.generic import ListView
from django.views.generic.edit import CreateView , DeleteView
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
class LoginView(LoginView):
    form_class = LoginForm
    template_name = 'login.html'
    success_url = reverse_lazy('dashboard')
    
# class StudentCreateView(SuccessMessageMixin,CreateView):
#     form_class = StudentForm
#     model= Student
#     # data = University.objects.all()
#     template_name = 'dashboard.html'
#     success_url = reverse_lazy('dashboard')
#     success_message = 'Result Uploded Successfully !!!!'

@login_required
def dashboard(request):
    data = University.objects.all()
    if request.method=="POST":
        university_id = request.POST.get('university_id')
        university_name = University.objects.get(id=university_id)
        registration_no = request.POST.get('registration_no')
        student_result = request.FILES.get('result')
        data1 = Student(user=request.user,university_name=university_name,registration_no=registration_no,student_result=student_result)
        data1.save()
        messages.success(request, 'Result Uploaded Succesfully')
    return render(request,"dashboard.html",{'data':data})  
    

class StudentListView(LoginRequiredMixin,ListView):
    template_name = 'studentdata.html'
    # queryset = Student.objects.all()  
    model = Student
    context_object_name = 'students'  
    
    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_staff:
            return queryset
            
        return queryset.filter(user__username=self.request.user.username)

class UniversityCreateView(LoginRequiredMixin,UserPassesTestMixin,SuccessMessageMixin,CreateView):
    form_class = UniversityForm
    model = University
    template_name = 'university.html'
    success_url = reverse_lazy('university')
    success_message = 'University Added Successfully !!!!'
    
    def test_func(self):
        return self.request.user.is_superuser
    
    def handle_no_permission(self):
        if self.request.user.is_authenticated:
            return redirect('dashboard') 
        else:
            return redirect('login')
 
class DeleteView(LoginRequiredMixin,DeleteView):
    model = Student
    success_url ="/studentdata/"
    template_name = 'delete.html'
    
def error_404(request, exception):
   context = {}
   return render(request,'404.html', context)
    

app/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>University Result</title>  
  <link rel="stylesheet" href="{% static 'css/dashboardstyle.css' %}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:rgb(106, 30, 30)">
        <a class="navbar-brand" href="#">RESULT</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            {% if request.user.is_superuser == True %}
            <li class="nav-item active">
                <a class="nav-link" href={% url 'university' %}>Add University<span class="sr-only"></span></a>
              </li>
            {% endif %}
            <li class="nav-item active">
              <a class="nav-link" href={% url 'dashboard' %}>Add Result<span class="sr-only"></span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href={% url 'studentdata' %}>Result Data<span class="sr-only"></span></a>
            </li>
          </ul>
        </div>
      </nav>
      <div class="page-content">
        {% block main-content %} {% endblock main-content %}
      </div>



</body>
</html>

app/templates/dashboard.html
{% extends 'base.html' %}
{% load static %}


{% block main-content %}

  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% if messages %}
    <div class="container"> 
      <div class="row">
        <div class='col-1'></div>
        <div class="col-10 mt-3" >
          {% for m in messages %}
          <div class="alert alert-success alert-dismissible fade show" role="alert">
            <h5 {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ m }}</h5>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          
            {% endfor %} 
        </div>
        <div class='col-1'></div>
      </div>
    </div>
        {% endif %}
    <div class="container-fluid">
      <div class="main">
        <div class="row">
          <div class="col-md-12">
            <div class="row">
              <div class="col-md-3"></div>
              <div class="col-md-6">
                <div class="result">
                  <div class="row">
                    <div class="col-md-6 col-sm-12">
                      <div class="side_img">
                        <img src={% static 'images/image1.jpg' %} alt="jhgfd" class="img_style" srcset="">
                      </div>
                    </div>
                    <div class="col-md-6  col-sm-12" style="background-color: rgb(106, 30, 30);padding:20px">
                      <div class="row">
                        <div class="col-md-12">

                          <div id="div_id_name" class="mb-3">
                            <label for="id_name" class="form-label requiredField label_field">
                              Name<span class="asteriskField">*</span> </label>
                            <select name="university_id" class="select form-select select_field" required id="id_name">
                              <option value="" selected>Select</option>
                              {% for i in data %}
                              <option value={{i.id}}>{{i.name}}</option>
                              {% endfor %}
                            </select>
                          </div>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-12">
                          <div id="div_id_registration_no" class="mb-3">
                            <label for="id_registration_no" class="form-label requiredField label_field">Registration no
                              <span class="asteriskField">*</span>
                            </label>
                            <input type="number" name="registration_no" class="numberinput form-control" required
                              id="id_registration_no">
                          </div>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-12">
                          <div id="div_id_result" class="mb-3"> <label for="id_result"
                              class="form-label requiredField label_field">
                              Result<span class="asteriskField">*</span> </label>
                            <div> <input type="file" name="result" class="form-control" accept="image/*" id="id_result"
                                required> </div>
                          </div>


                        </div>
                      </div>
                      <button type="submit" class='submit_btn'>
                        Add
                      </button>

                    </div>

                  </div>
                </div>

              </div>
              <div class="col-md-3"></div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </form>

{% endblock main-content %}

app/templates/delete.html
{% extends 'base.html' %}

{% block main-content %}
<div class='container mt-5'>
    <div class='row'>
        <div class='col-3'></div>
        <div class='col-6 text-center alert alert-danger'>
<form method="post">{% csrf_token %}
      <p>Are you sure you want to delete "{{ object }}"?</p>
       <input class="btn btn-sm bg-danger" type="submit" value="Confirm">
    </form>
</div>
    <div class='col-3'></div>
</div>
</div>
{% endblock main-content %}

app/templates/login.html
{% load static %}
{%load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
</head>

<body>

    <!-- <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Add">
    </form> -->
    <div class="main">
        <div class="sample">
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-md-10">
                    <h4>Login Here</h4>
            <form action="" method="post">
                {% csrf_token %} 
               
                <div id="div_id_username" class="mb-3 col-12 "> <label for="id_username" class="form-label requiredField" style="font-size: 20px; font-weight:bold;">
                    Email<span class="asteriskField">*</span> </label> <input type="text" name="username" maxlength="150"
                    class="textinput form-control" required id="id_username"> </div>
    
                    
            <div id="div_id_password" class="mb-3 "> <label for="id_password" class="form-label requiredField" style="font-size: 20px; font-weight:bold;">
                    Password<span class="asteriskField">*</span> </label> <input type="password" name="password"
                    autocomplete="current-password" class="passwordinput form-control" required id="id_password"> </div>
                <button class="rounded"><input type="submit" value="Add"></button>
                
            </form>
                </div>

                <div class="col-md-1"></div>
            </div>
            

        </div>
    </div>

</body>


<style>

.main{
    width: 100vw;
    height: 100vh;
    background-size: 100% 100%;
    background-blend-mode: multiply;
    background-image: url({% static 'images/img5.jpg' %}); 
    display: grid;
    place-items: center;
}

.sample{
    width: 40vw;
    height: 50vh;
    margin: auto;
    
} 
input{
    width: 99%;
    padding: 10px 0;
    margin-top: 5px;
    background: none;
    color: black;
    border: none;
    border-bottom: 5px;
}
h4{
    background-color: beige;
    text-align: center;
    padding: 10px;
    color: black;
}
button{
    background-color:beige;
    color: black;
    padding: 1px 0;
    width: 100%;
    border: none;
    margin-top: 10px;
    font-size: 25px;
}
</style>
    

app/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <nav class="navbar bg-body-tertiary fixed-top">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Offcanvas navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
            <div class="offcanvas-header">
              <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Offcanvas</h5>
              <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
              <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Dropdown
                  </a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="#">Action</a></li>
                    <li><a class="dropdown-item" href="#">Another action</a></li>
                    <li>
                      <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="#">Something else here</a></li>
                  </ul>
                </li>
              </ul>
              <form class="d-flex mt-3" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
              </form>
            </div>
          </div>
        </div>
      </nav>



</body>
</html>

app/templates/studentdata.html
{% extends 'base.html' %}

{% load static %}

{% block main-content %}
<div class="container">
    <div class="row">
        <div class="col-md-1 col-sm-12">

        </div>
        <div class="col-md-10 col-sm-12">
            <table class="table field_td">
                <thead>
                    <tr>
                        <th>University Name</th>
                        <th>Registration No</th>
                        <th>Result</th>
                        <th>Download</th>
                        {% if request.user.is_superuser == True %}
                        <th>Delete</th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for i in students %}
                    <tr>
    
                        <td>{{ i.university_name }}</td>
                        <td>{{ i.registration_no }}</td>
                        <td>{{i.student_result}}</td>
                        {% comment %} <td><img src="{{i.student_result.url}}" alt="" class="card-img-top" height="80" width="80"></td> {% endcomment %}
                        <td class="text-center"><a href="{{i.student_result.url}}" download><svg
                                    xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor"
                                    class="bi bi-file-earmark-arrow-down-fill" viewBox="0 0 16 16">
                                    <path
                                        d="M9.293 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.707A1 1 0 0 0 13.707 4L10 .293A1 1 0 0 0 9.293 0zM9.5 3.5v-2l3 3h-2a1 1 0 0 1-1-1zm-1 4v3.793l1.146-1.147a.5.5 0 0 1 .708.708l-2 2a.5.5 0 0 1-.708 0l-2-2a.5.5 0 0 1 .708-.708L7.5 11.293V7.5a.5.5 0 0 1 1 0z" />
                                </svg></a></td>
                        <td>
                            {% if request.user.is_superuser == True %}
                                          
                                          <div class="col-md-4">
                                            <a href="{% url 'delete' i.id %}" class="text-gray m-r-15"><svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                              </svg></a>
                                           </div> 
                                    
                                                                                
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-md-1 col-sm-12">

        </div>
    </div>
</div>
{% endblock main-content %}

app/templates/university.html
{% extends 'base.html' %}
{% load static %}

{% block main-content %}


  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    {% if messages %}
    <div class="container"> 
      <div class="row">
        <div class='col-1'></div>
        <div class="col-10 mt-5" >
          {% for m in messages %}
          <div class="alert alert-success alert-dismissible fade show" role="alert">
            <h5 {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ m }}</h5>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          
            {% endfor %} 
        </div>
        <div class='col-1'></div>
      </div>
    </div>
        {% endif %}
    <div class="container-fluid">
      <div class="main">
        <div class="row">
          <div class="col-md-12">
            <div class="row">
              <div class="col-md-3"></div>
              <div class="col-md-6">
                <div class="result">
                  <div class="row">
                    <div class="col-md-6 col-sm-12">
                      <div class="side_img">
                        <img src={% static 'images/image1.jpg' %} alt="jhgfd" class="img_style" srcset="">
                      </div>
                    </div>
                    <div class="col-md-6  col-sm-12" style="background-color: rgb(106, 30, 30);padding:20px">
                      <div class="row">
                        <div class="col-md-12">
                          <div id="div_id_name" class="mb-3">
                            <div id="div_id_name" class="mb-3"> <label for="id_name" class="form-label requiredField label_field">
                                Name<span class="asteriskField">*</span> </label> <input type="text" name="name" maxlength="100" class="textinput form-control" required id="id_name"> </div>
                          </div>
                        </div>
                      </div>
                      <button type="submit" class='submit_btn'>
                        Add
                      </button>

                    </div>

                  </div>
                </div>

              </div>
              <div class="col-md-3"></div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </form>



















{% endblock main-content %}